spring:
  application:
    name: eureka-server
security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123456
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://admin:123456@peer2:8762/eureka